baseURL = 'https://kongrooparadox.github.io'
languageCode = 'en-us'
title = 'Ramblings of an IT enthusiast'
theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "projects"
    pre = "<span data-feather='code'></span>"
    name = "Projects"
    url = "/projects/"
    weight = 1

  [[menu.main]]
    identifier = "skills"
    pre = "<span data-feather='tool'></span>"
    name = "Skills"
    url = "/skills/"
    weight = 2

  [[menu.main]]
    identifier = "github"
    url = "https://github.com/KongrooParadox"
    weight = 3
    pre = "<span data-feather='github'></span>"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false
